# Generated by Django 3.0.2 on 2020-02-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20200201_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
