# Generated by Django 3.0.2 on 2020-02-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20200202_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ('type',)},
        ),
        migrations.AddField(
            model_name='court',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
