# Generated by Django 3.0.2 on 2020-02-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20200210_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
