# Generated by Django 3.0.2 on 2020-02-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_auto_20200210_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.CharField(choices=[('Hard Court', 'Hard'), ('Grass Court', 'Grass'), ('Clay Court', 'Clay'), ('Carpet Court', 'Carpet')], max_length=100),
        ),
    ]
